deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: _site
  on:
    branch: master
env:
  matrix:
  - secure: Gq9zn6MdvymUT0hltx53069JdvPuEI3glxpY2d8/5/+F90TTiqchWAI9ezt0RdL6UpxU0MJLJ7y6KKAILFD5Y6vjj5gFcbSsyQZ69hGHwFSiZpGM9hmJXgVHFgd88QCH2qB23POXWXgHB+2D5nWitDGl/jeSInl1dsFGb+Wdz1o7CQlAO/dC7lRcfHkBfj9R4Rwaqxl4eh45kfS7pSnLiwx5e1zNfHkSKyg0NYRldTZN2ACGwOL784dq7k9M139x4j1IcBgACsYa6+TnvGeIp/uXQRWxlF/UFJnAXkdP5flUzMCyRbUYq3tACUoGFqExqyoZcS8uGb+gmoNmjFeBRO4W/Gy3eAtqu5/pWNYPiR+7Ot0tD+w4/ciYFFeaY1siMZdaNB2YQvtIC23Wz4unw+lnH0yEjCraikjFwid+u1SC/aPA7Q4x0NPZiMqpA4l7kNuukTuICSDo6yHtiMdpAcK9bQSnd5xa0846dtKBNarBulSwqOwOaukBDhwwITODcR8MdBOdoklDL1l4XJce6ZnsJ/ZE8FrHwPB9nzbylLd98JM34UbvOqKX2YYRr6H31HiYiBZ4dA4Eq9lAYIeNXax3e4Re/XP8YXpwTvtent2J5gX5x4IEoXTAwQk/Oj9niKY2j9Vi1Bd52dgVm7bp+ozFFh4pAQiYPZZWXkC3aPA=
